def help
	puts "Valid commands"
	puts "[] optional"
	puts "{} required"
	puts "add [+group] {descruption} [due today/tomorrow/(dd/mm/aaaa)]"
	puts "list [due today/tomorrow/(dd/mm/aaaa)]/[group]/[overdue]/[(any gruop]"
	puts "ac"
	puts "complete {a task number}"
	puts "save {file_name} without spaces" 
	puts "open {file_name} without spaces"
	puts "find {leters}"
	puts "set date_task {a date / empty}" 
	puts "set group  {a group / empty}"
	puts "help displays this message"
end
